using System.Text;

namespace Dev65.XObj;

/// <summary>
/// The <see cref="Code"/> class holds a series of generated bytes.
/// </summary>
public sealed class Code : Part
{
    private readonly StringBuilder _data = new StringBuilder();
    private readonly Module _module;

    /// <summary>
    /// Constructs a <see cref="Code"/> instance.
    /// </summary>
    /// <param name="module">The module associated with the code.</param>
    public Code(Module module)
    {
        _module = module;
    }

    /// <summary>
    /// Adds a byte value to the current code string.
    /// </summary>
    /// <param name="value">The value to add.</param>
    public void AddByte(long value)
    {
        _data.Append(Hex.ToHex(value, _module.GetByteSize() / 4));
    }

    /// <inheritdoc />
    public override string ToString()
    {
        return _data.ToString();
    }
}
